INSERT INTO leviathan.dbo.forums_moderators (forum_id, member_id) VALUES (1, 1);
INSERT INTO leviathan.dbo.forums_moderators (forum_id, member_id) VALUES (2, 1);
INSERT INTO leviathan.dbo.forums_moderators (forum_id, member_id) VALUES (2, 3);
INSERT INTO leviathan.dbo.forums_moderators (forum_id, member_id) VALUES (3, 1);
INSERT INTO leviathan.dbo.forums_moderators (forum_id, member_id) VALUES (4, 1);
INSERT INTO leviathan.dbo.forums_moderators (forum_id, member_id) VALUES (5, 1);
INSERT INTO leviathan.dbo.forums_moderators (forum_id, member_id) VALUES (6, 1);
INSERT INTO leviathan.dbo.forums_moderators (forum_id, member_id) VALUES (7, 1);
INSERT INTO leviathan.dbo.forums_moderators (forum_id, member_id) VALUES (8, 1);
